{% set name = "GridDataFormats" %}
{% set version = "0.4.1" %}
{% set sha256 = "b362662c2dc475e2a3895fe044eaaa9a707bd660fd109a63dac84a47236690a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - numpy
    - scipy

test:
  imports:
    - gridData

about:
  home: http://github.com/MDAnalysis/GridDataFormats
  license: LGPLv3
  license_file: COPYING.LESSER
  summary: 'Reading and writing of data on regular grids in Python'
  description: |
    The gridDataFormats package provides classes to unify reading and
    writing n-dimensional datasets. One can read grid data from files,
    make them available as a `Grid`_ object, and write out the data again.
  doc_url: http://www.mdanalysis.org/GridDataFormats/
  dev_url: https://github.com/MDAnalysis/GridDataFormats

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
