# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Ml3zF8ZpAZTSuO/0bxr+SvgvIciPsYA2DrglDd7GKVNEhX5ANEEqkEuRZdWTMvyg0zSGx0HbPo8W/4WFgFbjYjGdoMyKf7g91RlYdDMvw9MGCyibs6fdD3mlFgY39NHlGX32vwLKiyUbKJ/NhXcSzHR0mA9lc2lEoWqUcohLYDzQJ3ZuCOJU7HUeS/w326R1PvurCtRG4SFuvHq/AvPAh/UyI/ovD2pWszVJN+OhNVPVWBRzJlgL375oQXtV1cXAU5IsW85meITgcDg4K81vNiFrsudKvq5F7b/ypGiOOZO98BAM44xtiJpWwVzdxLmQcZC83QQD+6u+HfTgc25t7RVkBwKLkRBurNYOYe9g3vz9HdtdNBgPPLmkxct7oyx1e89K4oEj9xJW3AZ8MrYZQ0mjLuQ0KjWm8cQJZmAXEu7Y2zNhTABe60ssi/Edi5Pq3PAfqO9vY+cFZ+3ap/G+lZeF5URkm7IA2t0ntnsXNb6lW3OqjLnBZFFqaOdpItfzy9MmV4B89G4fqgfOR9XwAxpdrhF2iinSiZcSCixsPD0Crb5Lpv99gG8xxD/FFnS4L3Q8srH54aLCUmVeUAnaRhGEp+GcJOlNQzzw+r/b3g3fZL/FtAXzBNIV7Od7pCyPwQBQZNWjAkzb5ErMDPvqYYlyuPDL/1FQR3tLZ9wGQmg="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
