# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TGHDN6ZPLwWu2ej8lyAt4ddnkJ6b4iZqlqjAdfYHjC4oPXHoWCyoFWzaHOkppTab5ASUoTbfIca1tERPt31XKDZsZLIUZXmY52eRZW5ei6r351jZd7T2IqRC40NKfomek/8qAKLLRt5zAdCDgj8ekbBFkPQ50296gCee5+0NrG2vrGhAtjglNAbq4w1RglN9zAowJb8tLSOfLKk2kndr4rqyga7cQJNMNKMyXt1mi1AKrxr8JD0NDAtnzxNg8CGlW6zlln/WnmeBqYq30qyaRaqM3SJmZJlQ6IHB/HmmnSkjpsHXbZztcfgFVFW7uXlexw6ZHh45xXGnPzuwHYxSu7vO5/4nMsfCFNhI60hYVF4fkHy4jw+KApmlr4liEk+GIcVkcGPSdk1YJvyh63Ui0vcwq+ThPzLbp+5UQgy4AXLPHJ3PqBWw8lc7YP9vwb7/bJqWjMFWzBnuFO3tdGtFg97BYQEQZL/DftJQvzJdft6H8Cw/1dWPlLIrAdwzzis7gl2UCtFedMtoD6+yb85NrJzcd+AegS0+GvWIPB/MU37Z05kH2ysOPcKd6JmOqK80hm0FLV/XHClL+0cw20KSPltbaPbN8j7zeRsCjRetl3oHbMDWPqLtqx+80DvZ5iLMUWYfd1BKxad63pcrLA8FH81c6tD4Reab0o8jnDZEdXI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
