travis:
  secure:
    BINSTAR_TOKEN: TGHDN6ZPLwWu2ej8lyAt4ddnkJ6b4iZqlqjAdfYHjC4oPXHoWCyoFWzaHOkppTab5ASUoTbfIca1tERPt31XKDZsZLIUZXmY52eRZW5ei6r351jZd7T2IqRC40NKfomek/8qAKLLRt5zAdCDgj8ekbBFkPQ50296gCee5+0NrG2vrGhAtjglNAbq4w1RglN9zAowJb8tLSOfLKk2kndr4rqyga7cQJNMNKMyXt1mi1AKrxr8JD0NDAtnzxNg8CGlW6zlln/WnmeBqYq30qyaRaqM3SJmZJlQ6IHB/HmmnSkjpsHXbZztcfgFVFW7uXlexw6ZHh45xXGnPzuwHYxSu7vO5/4nMsfCFNhI60hYVF4fkHy4jw+KApmlr4liEk+GIcVkcGPSdk1YJvyh63Ui0vcwq+ThPzLbp+5UQgy4AXLPHJ3PqBWw8lc7YP9vwb7/bJqWjMFWzBnuFO3tdGtFg97BYQEQZL/DftJQvzJdft6H8Cw/1dWPlLIrAdwzzis7gl2UCtFedMtoD6+yb85NrJzcd+AegS0+GvWIPB/MU37Z05kH2ysOPcKd6JmOqK80hm0FLV/XHClL+0cw20KSPltbaPbN8j7zeRsCjRetl3oHbMDWPqLtqx+80DvZ5iLMUWYfd1BKxad63pcrLA8FH81c6tD4Reab0o8jnDZEdXI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
