travis:
  secure:
    BINSTAR_TOKEN: Ml3zF8ZpAZTSuO/0bxr+SvgvIciPsYA2DrglDd7GKVNEhX5ANEEqkEuRZdWTMvyg0zSGx0HbPo8W/4WFgFbjYjGdoMyKf7g91RlYdDMvw9MGCyibs6fdD3mlFgY39NHlGX32vwLKiyUbKJ/NhXcSzHR0mA9lc2lEoWqUcohLYDzQJ3ZuCOJU7HUeS/w326R1PvurCtRG4SFuvHq/AvPAh/UyI/ovD2pWszVJN+OhNVPVWBRzJlgL375oQXtV1cXAU5IsW85meITgcDg4K81vNiFrsudKvq5F7b/ypGiOOZO98BAM44xtiJpWwVzdxLmQcZC83QQD+6u+HfTgc25t7RVkBwKLkRBurNYOYe9g3vz9HdtdNBgPPLmkxct7oyx1e89K4oEj9xJW3AZ8MrYZQ0mjLuQ0KjWm8cQJZmAXEu7Y2zNhTABe60ssi/Edi5Pq3PAfqO9vY+cFZ+3ap/G+lZeF5URkm7IA2t0ntnsXNb6lW3OqjLnBZFFqaOdpItfzy9MmV4B89G4fqgfOR9XwAxpdrhF2iinSiZcSCixsPD0Crb5Lpv99gG8xxD/FFnS4L3Q8srH54aLCUmVeUAnaRhGEp+GcJOlNQzzw+r/b3g3fZL/FtAXzBNIV7Od7pCyPwQBQZNWjAkzb5ErMDPvqYYlyuPDL/1FQR3tLZ9wGQmg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
